src/indiedevlog.web/Controllers/PlanUpdatesController.cs
using indiedevlog.web.Managers;
using indiedevlog.web.Models;
using indiedevlog.web.Settings;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace indiedevlog.web.Controllers
{
    public class PlanUpdatesController : BaseController
    {
        public PlanUpdatesController(IOptions<GlobalSettings> globalSettings) : base(globalSettings.Value)
        {   
        }
        
        [Authorize]
        public ActionResult Index()
        {
            var model = new CreatePlanUpdateModel
            {
                Projects = new ProjectManager(_globalSettings).GetUserProjects(UserID)
            };

            return View(model);
        }

        [Route("/project/{projectName}")]
        public ActionResult Index(string projectName)
        {
            var result = new PlanManager(_globalSettings).GetProjectPlans(projectName);

            if (result.HasError)
            {
                return RedirectToAction("Error", "Home", result.ErrorException);
            }

            return View("ProjectPlanListing", result.ObjectValue);
        }
        
        [Authorize]
        public ActionResult CreatePlanUpdate(CreatePlanUpdateModel model)
        {
            var planResult = new PlanManager(_globalSettings).AddPlanUpdate(UserID, model.Subject, model.Body,
                model.SelectedProjectID);

            if (planResult)
            {
                return RedirectToAction("Index", "Home");
            }

            return View("Index", model);
        }
    }
}

src/indiedevlog.web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>indieDEVlog - @ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">indiedevlog</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="PlanUpdates" asp-action="Index">Create Post</a></li>
                        <li><a asp-area="" asp-controller="Projects" asp-action="Index">Projects</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Index">Login</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                    }
                </ul>
                
                @if (User.Identity.IsAuthenticated)
                {
                    <span class="welcomeBack"> Welcome back <strong>@User.Claims.ToList().FirstOrDefault(a => a.Type == "username").Value</strong>!</span>
                }
            </div>
        </div>
    </nav>
<div class="container body-content">
    <div class="row">
        <div class="col-md-12">
            @RenderBody()
        </div>
        <!--<div class="col-md-2">
            <div class="sidebarContainer">
                <input type="text" placeholder="search term here" />
            </div>
        </div>-->
    </div>

    <footer>
        <p>
            &copy; 2017 <a href="http://www.jarredcapellman.com/" target="_blank">Jarred Capellman</a><br/>
            Source code for the entire platform available at <a href="https://github.com/jcapellman/indiedevlog" target="_blank">GitHub</a>
        </p>
    </footer>
</div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/indiedevlog.web/Views/Shared/_PlanUpdate.cshtml
@model indiedevlog.web.Objects.PlanUpdates.PlanUpdateResponseItem

<div class="postContainer">
    <div class="header">
        <h3>@Model.Subject</h3>
        <h4><a href="/project/@Model.ProjectNameURLSafe" title="@Model.ProjectName">@Model.ProjectName</a></h4>
    </div>

    <div class="content">
        <p>@Html.Raw(Model.Body)</p>
        <div class="footer">
            <span class="user"><a href="/users/@Model.AuthorURLSafe">@Model.AuthorName</a></span>
            <span class="date">@Model.PostDate.ToString("MM-dd-yyyy")</span>
        </div>
    </div>
</div>